name: gtk_flutter
description: "Get to know Firebase with Flutter"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.0.2
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  go_router: ^14.0.1
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  provider: ^6.1.2
  firebase_ui_auth: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/codelab.png